apiVersion: v1
entries:
  sinfonia-tier2:
  - apiVersion: v2
    appVersion: v0.4.10
    created: "2025-07-26T14:07:07.58420601Z"
    description: A Helm chart for deploying Sinfonia-Tier2 in Kubernetes
    digest: 295d5777ca8da2107dbc807908b76798a5ed62712f131ca078e0ccc63799d94c
    name: sinfonia-tier2
    type: application
    urls:
    - sinfonia-tier2-0.4.10.tgz
    version: 0.4.10
generated: "2025-07-26T14:07:07.583216478Z"
